In [1]:
import numpy as np
a=np.zeros((10,5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [2]:
a=np.ones((2,4,4))
print(a)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [3]:
arr=np.arange(4)
print(arr)

[0 1 2 3]


In [4]:
arr.ndim

1

In [5]:
arr=np.arange(4),ndmin=2

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (4118937023.py, line 1)

In [6]:
a=np.arange(50).reshape(5,10)
print(a)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [7]:
a=np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [8]:
a=np.linspace(0,101,100)
print(a)

[  0.           1.02020202   2.04040404   3.06060606   4.08080808
   5.1010101    6.12121212   7.14141414   8.16161616   9.18181818
  10.2020202   11.22222222  12.24242424  13.26262626  14.28282828
  15.3030303   16.32323232  17.34343434  18.36363636  19.38383838
  20.4040404   21.42424242  22.44444444  23.46464646  24.48484848
  25.50505051  26.52525253  27.54545455  28.56565657  29.58585859
  30.60606061  31.62626263  32.64646465  33.66666667  34.68686869
  35.70707071  36.72727273  37.74747475  38.76767677  39.78787879
  40.80808081  41.82828283  42.84848485  43.86868687  44.88888889
  45.90909091  46.92929293  47.94949495  48.96969697  49.98989899
  51.01010101  52.03030303  53.05050505  54.07070707  55.09090909
  56.11111111  57.13131313  58.15151515  59.17171717  60.19191919
  61.21212121  62.23232323  63.25252525  64.27272727  65.29292929
  66.31313131  67.33333333  68.35353535  69.37373737  70.39393939
  71.41414141  72.43434343  73.45454545  74.47474747  75.49494949
  76.51515

In [9]:
l=[]
a=np.array([l])
print(a)
print(a.ndim)

[]
2


In [10]:
a=np.random.rand(4)
print(list(a))

[0.07427284206946327, 0.38593064866855065, 0.9811846031684303, 0.3945248734021173]


In [11]:
a=np.random.randint(1,100,1000000000)
print(a)
a[187766]

[65 82 60 ... 19  3 44]


49

In [12]:
a[99999999]

12

In [13]:
a=np.random.ranf((20,5))
print(a)

[[5.49660543e-01 4.69659215e-01 2.04762191e-01 2.88533080e-02
  5.31917622e-01]
 [8.42926433e-01 9.55646437e-01 2.59174844e-01 2.75421349e-01
  9.65469076e-02]
 [6.52882428e-02 2.28680473e-01 4.90187409e-01 2.14067324e-01
  9.81368818e-01]
 [7.91685074e-01 4.02858793e-01 1.99803249e-02 1.28897301e-01
  8.45023950e-01]
 [4.39654908e-01 8.41708941e-01 8.76532567e-01 5.36288129e-01
  1.65954167e-01]
 [9.76409839e-01 8.78465089e-01 6.11887610e-01 7.42666220e-01
  8.21254957e-01]
 [5.70729809e-02 8.54343477e-01 5.59345752e-01 1.99443137e-01
  8.19813606e-01]
 [5.69561950e-01 9.64860479e-01 1.65267678e-01 7.90221383e-01
  6.56399084e-01]
 [3.74779073e-01 1.05606377e-01 4.51779995e-01 4.93689063e-01
  8.22420600e-01]
 [7.13099803e-01 4.60229555e-02 1.60527171e-01 7.66536136e-04
  7.06650259e-01]
 [8.07157430e-01 9.19348181e-01 3.94944040e-01 1.98523078e-01
  1.35458935e-01]
 [8.56521443e-01 6.37518256e-01 3.35133865e-01 4.85879320e-01
  5.42878940e-01]
 [4.56891627e-01 2.55999704e-02 6.469768

In [14]:
import numpy as np
a=np.array(list(range(1,100)))
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


#### data types in python numpy are as int,float,bool,string,datetime,comples

In [15]:
a.dtype

dtype('int32')

In [16]:
a.astype('S')

array([b'1', b'2', b'3', b'4', b'5', b'6', b'7', b'8', b'9', b'10', b'11',
       b'12', b'13', b'14', b'15', b'16', b'17', b'18', b'19', b'20',
       b'21', b'22', b'23', b'24', b'25', b'26', b'27', b'28', b'29',
       b'30', b'31', b'32', b'33', b'34', b'35', b'36', b'37', b'38',
       b'39', b'40', b'41', b'42', b'43', b'44', b'45', b'46', b'47',
       b'48', b'49', b'50', b'51', b'52', b'53', b'54', b'55', b'56',
       b'57', b'58', b'59', b'60', b'61', b'62', b'63', b'64', b'65',
       b'66', b'67', b'68', b'69', b'70', b'71', b'72', b'73', b'74',
       b'75', b'76', b'77', b'78', b'79', b'80', b'81', b'82', b'83',
       b'84', b'85', b'86', b'87', b'88', b'89', b'90', b'91', b'92',
       b'93', b'94', b'95', b'96', b'97', b'98', b'99'], dtype='|S11')

In [17]:
arr=np.array(['ere','555t','6767'])

In [18]:
arr.dtype

dtype('<U4')

In [19]:
a=np.array([1,2,3,4,5],dtype='str')

In [20]:
a.dtype

dtype('<U1')

In [21]:
a.astype('str')

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [22]:
a=np.arange(1,32)
len(a)

31

In [23]:
a.dtype

dtype('int32')

In [24]:
a.astype(int)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [25]:
b=np.float32(a)

In [26]:
b.dtype

dtype('float32')

In [27]:
df=np.arange(1,101).reshape(10,10)

In [28]:
df

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [29]:
a=np.array([[2,3,4],[4,5,6]],ndmin=5)
print(a)
a.shape

[[[[[2 3 4]
    [4 5 6]]]]]


(1, 1, 1, 2, 3)

In [30]:
a=a.reshape(6)

In [31]:
a.reshape(3,2)

array([[2, 3],
       [4, 4],
       [5, 6]])

In [32]:
a.size

6

In [33]:
2*2*2*2*2*2*2*2*2*2

1024

In [34]:
a=np.arange(1,1025).reshape(2,2,2,2,2,2,2,2,2,2)

In [35]:
a=np.arange(1,13).reshape(2,3,2)
a

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [36]:
np.arange(5,7)

array([5, 6])

In [37]:
pow(2,10)

1024

In [38]:
pow(4,5)

1024

In [39]:
np.arange(1,1025).reshape(4,4,4,4,4)

array([[[[[   1,    2,    3,    4],
          [   5,    6,    7,    8],
          [   9,   10,   11,   12],
          [  13,   14,   15,   16]],

         [[  17,   18,   19,   20],
          [  21,   22,   23,   24],
          [  25,   26,   27,   28],
          [  29,   30,   31,   32]],

         [[  33,   34,   35,   36],
          [  37,   38,   39,   40],
          [  41,   42,   43,   44],
          [  45,   46,   47,   48]],

         [[  49,   50,   51,   52],
          [  53,   54,   55,   56],
          [  57,   58,   59,   60],
          [  61,   62,   63,   64]]],


        [[[  65,   66,   67,   68],
          [  69,   70,   71,   72],
          [  73,   74,   75,   76],
          [  77,   78,   79,   80]],

         [[  81,   82,   83,   84],
          [  85,   86,   87,   88],
          [  89,   90,   91,   92],
          [  93,   94,   95,   96]],

         [[  97,   98,   99,  100],
          [ 101,  102,  103,  104],
          [ 105,  106,  107,  108],
          [ 10

In [44]:
n = np.arange(1,6)
print(n.ndim,'\n')

for i in n:
    print(i)

1 

1
2
3
4
5


In [55]:
a=np.arange(1,49).reshape(3,4,4)
print(a)
for i1 in a:
    for i2 in i1:
        for i3 in i2:
            print(i3)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]
  [25 26 27 28]
  [29 30 31 32]]

 [[33 34 35 36]
  [37 38 39 40]
  [41 42 43 44]
  [45 46 47 48]]]
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48


In [57]:
for i in np.nditer(a):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48


In [61]:
a=np.arange(1,10).reshape(3,3)
print(a)
for i in np.nditer(a):
    print(i)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
2
3
4
5
6
7
8
9


In [67]:
np.full((3,3,3),'(-_-)')

array([[['(-_-)', '(-_-)', '(-_-)'],
        ['(-_-)', '(-_-)', '(-_-)'],
        ['(-_-)', '(-_-)', '(-_-)']],

       [['(-_-)', '(-_-)', '(-_-)'],
        ['(-_-)', '(-_-)', '(-_-)'],
        ['(-_-)', '(-_-)', '(-_-)']],

       [['(-_-)', '(-_-)', '(-_-)'],
        ['(-_-)', '(-_-)', '(-_-)'],
        ['(-_-)', '(-_-)', '(-_-)']]], dtype='<U5')