In [1]:
import numpy as np
import pandas as pd

In [9]:
a= np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [10]:
a.ndim

1

In [17]:
l= [1,2,3]
a=np.array([[l,l,l],[l,l,l]])
print(a)
print(a.ndim)

[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]]]
3


In [20]:
a=np.arange(1,101)
print(a)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [22]:
a=np.arange(1,100000001)
c=0
for i in a:
    c+=1
print(c)

100000000


In [26]:
a[24:50]

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50])

In [33]:
a=np.arange(1,301).reshape(3,20,5)

In [37]:
a[0][0][2]

3

In [51]:
a[0:1][0][1:4]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [48]:
a

array([[[  1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20],
        [ 21,  22,  23,  24,  25],
        [ 26,  27,  28,  29,  30],
        [ 31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40],
        [ 41,  42,  43,  44,  45],
        [ 46,  47,  48,  49,  50],
        [ 51,  52,  53,  54,  55],
        [ 56,  57,  58,  59,  60],
        [ 61,  62,  63,  64,  65],
        [ 66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75],
        [ 76,  77,  78,  79,  80],
        [ 81,  82,  83,  84,  85],
        [ 86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100]],

       [[101, 102, 103, 104, 105],
        [106, 107, 108, 109, 110],
        [111, 112, 113, 114, 115],
        [116, 117, 118, 119, 120],
        [121, 122, 123, 124, 125],
        [126, 127, 128, 129, 130],
        [131, 132, 133, 134, 135],
        [136, 137, 138, 139, 140],
        [141, 142,

In [64]:
a=np.arange(1,101).reshape(10,10)

In [69]:
a=pd.DataFrame(a)

In [74]:
a[[0]]

0
0   1
1  11
2  21
3  31
4  41
5  51
6  61
7  71
8  81
9  91