In [3]:
a = 3

In [4]:
a+2

5

In [5]:
type(a)

int

In [6]:
print(type(a))

<class 'int'>


In [9]:
int(2.9999)

2

In [10]:
float(2)

2.0

In [11]:
str(2)

'2'

In [19]:
a= "Devesh"
print(f"hello mister <-_->{a}")

hello mister <-_->Devesh


In [21]:
2**3

8

In [32]:
4==4 and 6==2

False

In [35]:
not 2==3

True

In [40]:
a = str.lower(input())
if a == "ind":
    print("Hello its right")

 IND


Hello its right


In [52]:
a=10
b=45
c=0
print(f"A is {a} and b is {b}")

A is 10 and b is 45


In [53]:
c=a
a=b
b=c


print(f"A is {a} and b is {b}")

A is 45 and b is 10


In [54]:
year=int(input())
if year%

SyntaxError: invalid syntax (3257467783.py, line 2)

In [59]:
a=int(input())
if a%5==0:
    print('Fully divided by 5')
else: 
    print("Not fully divided by 5")

 26


Not fully divided by 5


In [62]:
a =int(input("a = "))
b =int(input("b = "))
if a==b:
    print("They are equal")
elif a>b:
    print("A is bigger")
else:
    print("B is bigger")

a =  9
b =  8


A is bigger


In [65]:
num = int(input())
if num%5==0 and num%7==0:
    print("It can be divided by 5 and 7 both")
else:
    print("It  cannot")

 35


It can be divided by 5 and 7 both


In [69]:
a = int(input("A = "))
b = int(input("B = "))
c = int(input("C = "))
if a>b and a>c:
    print("A is largest")
elif b>a and b>c:
    print("B is largest")
elif c>a and c>b:
    print("C is largest")
else:
    print("they are all equal")

A =  12
B =  13
C =  12


B is largest


In [78]:
year = int(input("Enter Year = "))
if (year%100==0 and year %400==0) or (year%4==0):
    print("Its a Leap year")
else:
    print("Its not a leap year")


Enter Year =  2100


Its a Leap year


In [86]:
year = int(input("Enter Year = "))
if year%100==0:
    if year%400==0 :
        print("Leap year")
    else:
        print("Its not a leap year")

else:
    if year%4==0:
            print("Leap year")
    else:
        print("Its not a leap year")

Enter Year =  2436


Leap year


In [22]:
a=56
b=88
print(id(a),id(b))

140726749207048 140726749208072


In [27]:
b=56
print(id(b),id(a))

140726749207048 140726749207048


In [28]:
a is b

True

In [5]:
print(id(a),id(b))

140726749207048 140726749207048


In [12]:
l = [1,2,3,4,5]
fs = frozenset(l)
s = set(l)

In [14]:
s

{1, 2, 3, 4, 5}

In [15]:
type(s)

set

In [17]:
s.pop(2)

TypeError: set.pop() takes no arguments (1 given)

In [4]:
a = [1,2]
b=[1,2]
id(a),id(b)

(2441655238016, 2441655243712)

In [7]:
a is b

False

In [6]:
a==b

True

In [16]:
print("IOTA" ,"Academy" ,"is", "the" ,"best" ,"institute",end="*_*")
print("Hello")

IOTA Academy is the best institute*_*Hello


In [18]:
-install kivy

SyntaxError: invalid syntax (809726506.py, line 1)

In [29]:
day = str.lower(input("Enter day- "))
days = ["sunday",'monday','tuesday','wednesday','thursday','friday','saturday']
if day in days:
    if day=="sunday":
        print("Yeahhh 😁")
    else:
        print("Nooo 😭")
else:
    print("Enter a valed day name")

Enter day-  moNDAY


Nooo 😭


In [32]:
a = 0123

SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers (1293963658.py, line 1)

In [33]:
"50"+"50"

'5050'

In [34]:
"50"&"50"

TypeError: unsupported operand type(s) for &: 'str' and 'str'

In [36]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [43]:
for i in range(1,11,2):
    print(i,end=", ")

1, 3, 5, 7, 9, 

In [45]:
l= [1,2,3,["hello"]]
lst = [1,2,3,l]
print(lst)

[1, 2, 3, [1, 2, 3, ['hello']]]


In [47]:
len(l)

4

In [48]:
a = l.copy()

In [49]:
a

[1, 2, 3, ['hello']]

In [53]:
l.count(2)

1

In [59]:
l=[1,1,1,1,2,1,2,2,2,3,3,43,3,7,3,999,9,9,9,9,9,9,9,99,9,9,99]

In [60]:
l.count(1)

5

In [71]:
unique = list(set(l))
unique.sort()

In [72]:
for i in unique:
    print(f"{i} = {l.count(i)}")

1 = 5
2 = 4
3 = 4
7 = 1
9 = 9
43 = 1
99 = 2
999 = 1


In [75]:
type(sorted((3,2,1)))

list

In [76]:
type((3,2,1))

tuple

In [131]:
l = [3,6,8,4,6,3,2,8,23]

In [132]:
l.remove(6)
l

[3, 8, 4, 6, 3, 2, 8, 23]

In [134]:
l.insert(1,99)

In [142]:
l.pop()
l

[3, 2]

In [124]:
for i in range(len(l)-1):
    for j in range(len(l)-1-i):
        if l[j]>l[j+1]:
            l[j],l[j+1]=l[j+1],l[j]

In [125]:
l

[2, 3, 3, 4, 6, 6, 8, 8, 23]

In [112]:

# Input: list of numbers
numbers = [64, 34, 25, 12, 22, 11, 90]

# Bubble Sort algorithm
for i in range(len(numbers) - 1):
    for j in range(len(numbers) - 1 - i):
        if numbers[j] > numbers[j + 1]:
            # Swap if the current number is greater than the next number
            numbers[j], numbers[j + 1] = numbers[j + 1], numbers[j]

# Displaying the sorted list
print("Sorted list:", numbers)

Sorted list: [11, 12, 22, 25, 34, 64, 90]


In [18]:
l = [1,2,4,7,5,3,1,4]
l[0:5:2]

[1, 4, 5]

In [19]:
l[-1][0]

TypeError: 'int' object is not subscriptable

In [4]:
t = ()
type(t)

tuple

In [5]:
t = 'hello','world'

In [6]:
type(t)

tuple

In [10]:
(91,2,3)+(1,)

(91, 2, 3, 1)

In [12]:
t = tuple([6,7,8])

In [14]:
type(t)

tuple

In [37]:
l=[1,2,3,4,5]
print(l[::-1][1::2])


[4, 2]


In [38]:
t = (1,2,3,['list','two'])

In [40]:
type(t[3])

list

In [41]:
t[3].append('hello')

In [43]:
type(t)

tuple

In [46]:
sorted((5,8,3))

[3, 5, 8]

In [48]:
t = (5,7,67)
sum(t)

79

In [52]:
min(t)

5

In [53]:
l1 =['maths','physics','science']
l2 = ['economics','science','maths','hindi']

In [56]:
common = set(l1)&set(l2)
common

{'maths', 'science'}

In [60]:
all_sub = set(l1)|set(l2)
all_sub

{'economics', 'hindi', 'maths', 'physics', 'science'}

In [68]:
s1 = set(l1)
s2 = set(l2)
s1.intersection(s2)

{'maths', 'science'}

In [70]:
s1-s2,s2-s1

({'physics'}, {'economics', 'hindi'})

In [71]:
s1^s2

{'economics', 'hindi', 'physics'}

In [76]:
s = set()

In [77]:
type(s)

set

In [78]:
s = {2,3,4,4,4}

In [84]:
s.update('abcd')
s

{2, 3, 4, 5, 'a', 'b', 'c', 'd'}

In [89]:
l = [1,2,3]
l[3]= 8

IndexError: list assignment index out of range

In [86]:
l

[8, 2, 3]

In [107]:
s = {1,2,3}
s1 = {5,6,7}

In [94]:
s.pop()

KeyError: 'pop from an empty set'

In [100]:
s.remove(2)
s

set()

In [97]:
s

{2, 3}

In [101]:
s

set()

In [105]:
s.update(s1)

In [106]:
s

{1, 2, 3, 5, 6, 7}

In [113]:
s = {1,2,3,7}
s1 = {5,6,7,3,2}

In [114]:
s1.difference(s)

{5, 6}

**_hello this is a raw cell_**

In [20]:
str(456)

'456'

In [21]:
[400,50,6]

[400, 50, 6]

In [50]:
num = 456
strnum = str(num)
l=[]

In [51]:
count = (len(strnum)-1)
for i in strnum:
    l.append(str(i)+(count*"0"))
    count-=1

In [52]:
l


['400', '50', '6']

In [56]:
'a'+'b'

'ab'

In [64]:
'hello world'.split(" ")

['hello', 'world']

In [76]:
for i in range(2,11):
    print()
    print(f"Table of {i}")
    for j in range(1,11):
        print(f'{i} x {j} = ',i*j)


Table of 2
2 x 1 =  2
2 x 2 =  4
2 x 3 =  6
2 x 4 =  8
2 x 5 =  10
2 x 6 =  12
2 x 7 =  14
2 x 8 =  16
2 x 9 =  18
2 x 10 =  20

Table of 3
3 x 1 =  3
3 x 2 =  6
3 x 3 =  9
3 x 4 =  12
3 x 5 =  15
3 x 6 =  18
3 x 7 =  21
3 x 8 =  24
3 x 9 =  27
3 x 10 =  30

Table of 4
4 x 1 =  4
4 x 2 =  8
4 x 3 =  12
4 x 4 =  16
4 x 5 =  20
4 x 6 =  24
4 x 7 =  28
4 x 8 =  32
4 x 9 =  36
4 x 10 =  40

Table of 5
5 x 1 =  5
5 x 2 =  10
5 x 3 =  15
5 x 4 =  20
5 x 5 =  25
5 x 6 =  30
5 x 7 =  35
5 x 8 =  40
5 x 9 =  45
5 x 10 =  50

Table of 6
6 x 1 =  6
6 x 2 =  12
6 x 3 =  18
6 x 4 =  24
6 x 5 =  30
6 x 6 =  36
6 x 7 =  42
6 x 8 =  48
6 x 9 =  54
6 x 10 =  60

Table of 7
7 x 1 =  7
7 x 2 =  14
7 x 3 =  21
7 x 4 =  28
7 x 5 =  35
7 x 6 =  42
7 x 7 =  49
7 x 8 =  56
7 x 9 =  63
7 x 10 =  70

Table of 8
8 x 1 =  8
8 x 2 =  16
8 x 3 =  24
8 x 4 =  32
8 x 5 =  40
8 x 6 =  48
8 x 7 =  56
8 x 8 =  64
8 x 9 =  72
8 x 10 =  80

Table of 9
9 x 1 =  9
9 x 2 =  18
9 x 3 =  27
9 x 4 =  36
9 x 5 =  45
9 x 6 =  54

In [83]:
num = int(input("Which table you want"))
print(f"Table of {num} is here - ") 
for i in range(10):
    print(f"{num} x {i} = {num*i}")

Which table you want 7


Table of 7 is here - 
7 x 0 = 0
7 x 1 = 7
7 x 2 = 14
7 x 3 = 21
7 x 4 = 28
7 x 5 = 35
7 x 6 = 42
7 x 7 = 49
7 x 8 = 56
7 x 9 = 63


In [86]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [93]:
l = [1,2,3,4,5,6,7,8,9,10]
num = int(input("enter a number between 1-10"))
for i in l:
    if i != num:
        print(f"{i} is not your number ")
    else:
        print(f"---->yes {i} was your number")
        break

enter a number between 1-10 1


---->yes 1 was your number


In [113]:
num = int(input("Enter a number - "))
for i in range(2,num):
    if num%i==0:
        print("Its not a prime")
        break
else:
        print("Prime")

Enter a number -  51


Its not a prime


In [108]:
for i in range(5):
    print(i)
else:
    print("Loop completed without break")


0
1
2
3
4
Loop completed without break


In [110]:
for i in range(5):
    if i == 3:
        break
    print(i)
else:
    print("Loop completed without break")



0
1
2


In [133]:
print("print all the prime numbers from start to end")
start = int(input("Start - "))
end = int(input("End - "))
prime_list = []
for i in range(start,end+1):
    if checkprime(i):
        prime_list.append(i)
        
print(prime_list)

print all the prime numbers from start to end


Start -  5
End -  30


[5, 7, 11, 13, 17, 19, 23, 29]


In [124]:
def checkprime(num):
    for i in range(2,num):
        if num%i==0:
            result = False
            break
    else:
        result = True
    return result

False

In [123]:
(100**0.5)+1

11.0

## making a fibonacci series till nth term

In [143]:
num = int(input("Enter a number"))
l = [0,1]
for i in range(num):
    l.append(l[-1]+l[-2])

print("Fibonacci series is - ",l[:num])

Enter a number 2


Fibonacci series is -  [0, 1]


In [145]:
l =[1,2,3,4,5,6,7,8]
l[::-1]


[8, 7, 6, 5, 4, 3, 2, 1]

In [156]:
l1 = ["M", "na", "i", "IO"]
l2 = ["y", "me", "s", "TA"]
l3 = []
for i in range(len(list1)):
    l3.append(l1[i]+l2[i])
l3

['My', 'name', 'is', 'IOTA']

In [152]:
l1[1]

'na'

In [153]:
'na+'+'h'

'na+h'

In [159]:
l = [4,7,3,6]
l1 =[]
for i in l:
    l1.append(i**2)
l1

[16, 49, 9, 36]

In [160]:
l1 = [10, 20, 30, 40]
l2 = [100, 200, 300, 400]

for i in range(len(l1)):
    print(l1[i],l2[-(i+1)])

10 400
20 300
30 200
40 100


In [161]:
import random

In [181]:
[ random.randint(1,100) for i in range(10)]

[46, 30, 69, 51, 15, 90, 74, 27, 40, 15]

In [186]:
a =10000
b = 10000
id(a),id(b)

(1492755757968, 1492755758416)

In [190]:
x = [10]
y = x

y = y.append(11)
x

[10, 11]

In [191]:
amount = 1000000
loanint = 0.095
investint = 0.25
time =5 

In [194]:
(amount*investint)*5

1250000.0

In [204]:
a = input()
print(a)

 56


56


In [205]:
type(a)

str

In [206]:
id(a)

1492810865072

In [208]:
help(print)

Help on built-in function print in module builtins:

print(*args, sep=' ', end='\n', file=None, flush=False)
    Prints the values to a stream, or to sys.stdout by default.
    
    sep
      string inserted between values, default a space.
    end
      string appended after the last value, default a newline.
    file
      a file-like object (stream); defaults to the current sys.stdout.
    flush
      whether to forcibly flush the stream.



In [209]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [211]:
help(random.randint)

Help on method randint in module random:

randint(a, b) method of random.Random instance
    Return random integer in range [a, b], including both end points.



In [212]:
a = [1,67]

In [218]:
help(enumerate)

Help on class enumerate in module builtins:

class enumerate(object)
 |  enumerate(iterable, start=0)
 |  
 |  Return an enumerate object.
 |  
 |    iterable
 |      an object supporting iteration
 |  
 |  The enumerate object yields pairs containing a count (from start, which
 |  defaults to zero) and a value yielded by the iterable argument.
 |  
 |  enumerate is useful for obtaining an indexed list:
 |      (0, seq[0]), (1, seq[1]), (2, seq[2]), ...
 |  
 |  Methods defined here:
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __iter__(self, /)
 |      Implement iter(self).
 |  
 |  __next__(self, /)
 |      Implement next(self).
 |  
 |  __reduce__(...)
 |      Return state information for pickling.
 |  
 |  ----------------------------------------------------------------------
 |  Class methods defined here:
 |  
 |  __class_getitem__(...) from builtins.type
 |      See PEP 585
 |  
 |  --------------------------------------------------------

In [226]:
a = [1,2,3,5,6,7,4,3,9,5]
b = list(enumerate(a,start=1))

In [227]:
print(b)

[(1, 1), (2, 2), (3, 3), (4, 5), (5, 6), (6, 7), (7, 4), (8, 3), (9, 9), (10, 5)]


In [231]:
num = int(input())
for i in b:
    if i[0]==num:
        print('yeah found it')
    else:
        print("-")

 6


-
-
-
-
-
yeah found it
-
-
-
-


In [232]:
min(a)

1

In [239]:
max(list("hello123_"))

'o'

In [246]:
3!=7

True

In [248]:
3==3 and 'hello'=='hello5'

False

In [249]:
bin(16)

'0b10000'

In [256]:
bin(5)[2:]

'101'

In [261]:
a,b = 90,80

(90, 80)

## vowels counter

In [269]:
text = "hello AAii i am learning python"
count = 0
vowels = list('aeiou')
for i in text:
    if i in vowels:
        count+=1
print(f"Total numbers of Vowels in text are {count}")

Total numbers of Vowels in text are 10


## random password generator

In [271]:
import random

In [290]:
char = list('abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890!@#$%^&*_-+')
random.shuffle(char)
num = int(input("How many charector of password you want? "))
password = ""
for i in range(num):
    r = random.randint(0,len(char)-1)
    password += char[r]
print(f"Here is your password {password}")


How many charector of password you want?  20


Here is your password K!j7&tv8jvV&Cf8mC&7e


## Prime number finder

In [294]:
num = int(input("Enter a number"))
for i in range(2,num):
    if num%i==0:
        print("Its not a prime")
        break
else:
    print("Prime")

Enter a number 69


Its not a prime


In [297]:
a = [1,2,3]
a.extend("abcd")
print(a)

[1, 2, 3, 'a', 'b', 'c', 'd']


In [298]:
a = [1,2,3]
a.append("abcd")
print(a)

[1, 2, 3, 'abcd']


In [303]:
a.index(1)

0

In [306]:
a.insert(0,999)

In [307]:
a

[999, 1, 2, 3, 'abcd', 0]

In [308]:
a= [4,9,3,5,7,3]

In [309]:
b = tuple(a)

In [311]:
print(a)
print(b)

[4, 9, 3, 5, 7, 3]
(4, 9, 3, 5, 7, 3)


In [316]:
sorted(a,reverse=True)

[9, 7, 5, 4, 3, 3]

In [313]:
sorted(b)

[3, 3, 4, 5, 7, 9]

In [317]:
b

(4, 9, 3, 5, 7, 3)

In [319]:
[1,2,3]+[4,5,0]

[1, 2, 3, 4, 5, 0]

In [320]:
list1 = ["Hello ", "take "]
list2 = ["Dear", "Sir"]
l3 = []
for i in list1:
    for j in list2:
        l3.append(i+j)
l3
    

['Hello Dear', 'Hello Sir', 'take Dear', 'take Sir']

# Q5

In [323]:
list1 = [10, 20, 30, 40]
list2 = [100, 200, 300, 400]

for i in range(len(list1)):
    print(list1[i],list2[-i-1])

10 400
20 300
30 200
40 100


# Q6

In [325]:
list1 = ["Dhawan", "", "Jadeja", "Dhoni", "", "Virat"]
for i in list1:
    if i=="":
        list1.remove(i)
list1

['Dhawan', 'Jadeja', 'Dhoni', 'Virat']

# Q7

In [327]:
list1 = [10, 20, [300, 400, [5000, 6000], 500], 30, 40]
list1[2][2].append(7000)

In [328]:
list1

[10, 20, [300, 400, [5000, 6000, 7000], 500], 30, 40]

# Q8

In [329]:
list1 = ["a", "b", ["c", ["d", "e", ["f", "g"], "k"], "l"], "m", "n"]
sub_list = ["h", "i", "j"]
list1[2][1][2].extend(sub_list)
list1

['a', 'b', ['c', ['d', 'e', ['f', 'g', 'h', 'i', 'j'], 'k'], 'l'], 'm', 'n']

# Q9

In [332]:
list1 = [5, 10, 15, 20, 25, 50, 20]
for i in range(len(list1)):
    if list1[i] ==20:
        list1[i] = 200
        break
list1

[5, 10, 15, 200, 25, 50, 20]

# Q10

In [343]:
l1 = [5, 20, 15, 20, 25, 50, 20]
l2 = []
for i in range(len(l1)):
    if l1[i]!=20:
        l2.append(l1[i])
    
l2

[5, 15, 25, 50]

# Creating a linear search algorithm

In [344]:
cards =[random.randint(1,100) for i in range(12)]

In [346]:
cards = sorted(cards,reverse=True)

In [354]:
cards

[95, 88, 60, 54, 48, 45, 42, 33, 32, 31, 22, 12]

In [358]:
query = 99
# we have to find this query in that list and return the position

In [359]:
for i in range(len(cards)):                     # starting a loop for every element
    if cards[i]==query:                         # checking if the element equal query
        print(f"Its in {i}th position")         # if yes printing its position
        break                                   # the moment we found the element break the loop which will not search if there is anathor element same as query
else:
    print("Did not fount query")                # if the loop did not break this statement will run

Did not fount query


In [361]:
tuple([5])

(5,)

In [363]:
set(5)

TypeError: 'int' object is not iterable

In [369]:
print("hello",end="---")
print("world")

hello---world


In [370]:
space = 6
star = 1
for i in range(1,7):
    print(space*" ",star*'*')
    space -=1
    star+=2


       *
      ***
     *****
    *******
   *********
  ***********


In [371]:
print("hello\nworld")

hello
world


In [374]:
char = "a"+"b"
char

'ab'

In [375]:
char+"hello"

'abhello'

### can you convert this 'o' to '---'?

In [378]:
text = "hello world"
new_text = ""
for i in text:
    if i=="o":
        new_text+="---"
    else:
        new_text+=i
print(new_text)

hell--- w---rld


In [381]:
"+".join(['abcd','hello'])

'abcd+hello'

In [387]:
text = "hello world"
text = text.replace("o","---")
print(text)

hell--- w---rld


In [389]:
num = "$45,87,800"

In [394]:
print(num.replace("$","").replace(",",""))

4587800


In [396]:
import pandas as pd

In [398]:
df = pd.DataFrame([2,4,6,7,9,9,7,12,56,4,3,5,6,7,90])

In [403]:
import numpy as np

In [404]:
np.percentile(df,25)

4.5

In [405]:
np.sum(df)

0    227
dtype: int64

In [407]:
%timeit np.sum(df)

274 µs ± 41.9 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [417]:
print("Hello\"world\"")

Hello"world"


In [418]:
a=b=c="hello"
print(a,b,c)

hello hello hello


In [420]:
print("hello "+"World")

hello World


In [432]:
x = "awesome"
def first():
    global y 
    
    y = "world"
    print("hello",x,y)
    
first()
print(x)
print(y)

hello awesome world
awesome
world


In [435]:
x = range(1,100,3)
for i in x:
    print("* ",end='')

* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 

In [437]:
type(5j+3)

complex

In [438]:
complex(56)

(56+0j)

In [439]:
int(45+0j)

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'complex'

## guess my number game

In [443]:
import random 
Num = random.randint(1,100)
TryCount = 1
print("Guess my number between 1 and 100")
Guess = int(input("Enter your number - "))
while True:
    if Num == Guess:
        break
    else:
        if Guess>Num:
            Guess = int(input("Enter a short number"))
        else:
            Guess = int(input("Enter a Greater number"))
        TryCount +=1
    pass
print(f"You have guess the number right {Num} in {TryCount} try's")

Guess my number between 1 and 100


Enter your number -  50
Enter a short number 25
Enter a short number 12
Enter a short number 8
Enter a short number 5
Enter a short number 3
Enter a short number 2
Enter a short number 1


You have guess the number right 1 in 8 try's


In [452]:
for i in range(30):
    if i%2==1:
        print("| * |"*10)
    else:
        print("-----"*10)

--------------------------------------------------
| * || * || * || * || * || * || * || * || * || * |
--------------------------------------------------
| * || * || * || * || * || * || * || * || * || * |
--------------------------------------------------
| * || * || * || * || * || * || * || * || * || * |
--------------------------------------------------
| * || * || * || * || * || * || * || * || * || * |
--------------------------------------------------
| * || * || * || * || * || * || * || * || * || * |
--------------------------------------------------
| * || * || * || * || * || * || * || * || * || * |
--------------------------------------------------
| * || * || * || * || * || * || * || * || * || * |
--------------------------------------------------
| * || * || * || * || * || * || * || * || * || * |
--------------------------------------------------
| * || * || * || * || * || * || * || * || * || * |
--------------------------------------------------
| * || * || * || * || * || * ||

In [453]:
import numpy as np

In [456]:
np.array([2,5,3,4])

array([2, 5, 3, 4])

In [493]:
np.arange(1,10000000).sum()

-2014260032

In [494]:
count  = 0
list1 = list(range(1,10000000))
for i in list1:
    count +=i
print(count)

49999995000000


In [476]:
np.arange(1,11).sum()

55

In [515]:
np.zeros((2,3,4),dtype="int")

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [513]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [517]:
cal()

NameError: name 'cal' is not defined

In [520]:
arr = np.arange(100).reshape(2,50)

In [522]:
arr.ndim

2

In [523]:
arr.shape

(2, 50)

In [525]:
np.size(arr)

100

In [526]:
np.shape(arr)

(2, 50)

In [527]:
np.ndim(arr)

2

In [538]:
arr[0][2:4]

array([2, 3])

In [539]:
a = np.array([1,2,3,4,5,6])

In [544]:
a[0] = 90
a

array([90,  2,  3,  4,  5,  6])

In [551]:
arr[:,1:5]

array([[ 1,  2,  3,  4],
       [51, 52, 53, 54]])

In [552]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98, 99]])

In [556]:
arr[1,16]

66

In [558]:
arr = np.array([[1,2,3,4,5],[8,7,6,5,4]])

In [559]:
arr

array([[1, 2, 3, 4, 5],
       [8, 7, 6, 5, 4]])

In [569]:
a = np.array([1,2,3])
b = np.array([8,7,9])
c= np.concatenate([a,b,c])

In [570]:
c

array([1, 2, 3, 8, 7, 9, 1, 2, 3, 8, 7, 9, 1, 2, 3, 8, 7, 9, 1, 2, 3, 8,
       7, 9])

In [573]:
a = "hello"
a = a.upper()
a

'HELLO'

In [575]:
a = a.lower()
a

'hello'

In [577]:
a.split("e")

['h', 'llo']

In [578]:
a = "hello my name is devesh"
print(a.split())

['hello', 'my', 'name', 'is', 'devesh']


In [579]:
b = a.split()

In [581]:
"-+-".join(b)

'hello-+-my-+-name-+-is-+-devesh'

In [582]:
int

int

In [584]:
int(45.89)

45

In [591]:
a = "hello world"


In [592]:
"hello world".upper()

'HELLO WORLD'

In [594]:
"hello".replace(" ","o")

'hello'

In [596]:
age = 36
txt = "My name is John, I am " + 'age'
print(txt)

My name is John, I am age


In [597]:
price = 59
txt = f"The price is {price} dollars"
print(txt)

The price is 59 dollars


In [598]:
price = 59
txt = f"The price is {price:.2f} dollars"
print(txt)

The price is 59.00 dollars


In [609]:
bool()

False

In [612]:
12//3

4

In [616]:
2-1 == (2/2)

True

In [618]:
True != False

True

In [619]:
a = 10
A = 11

In [629]:
mango1 = 12

12

In [630]:
"hell0".isalpha()

False

In [631]:
"343".isdigit()

True

In [634]:
"3432jfijs".isalnum()

True

In [638]:
len("          hrllo world     ".strip())

11

In [639]:
__hash__(34)

NameError: name '__hash__' is not defined

In [641]:
hash([45])

TypeError: unhashable type: 'list'

In [642]:
a = set()

In [643]:
type(a)

set

In [649]:
a = 10
b = 20
print(a)
print(b)

10
20


In [656]:
a = {1,2,3,44,4,4,4}
a.discard(4)
a

{1, 2, 3, 44}

In [655]:
a = {1,2,3}
a.remove(4)
a

KeyError: 4

In [657]:
a = {1,2,3,4,5}
a.pop()

1

In [663]:
a.pop()

KeyError: 'pop from an empty set'

In [664]:
a

set()

In [667]:
a = {1,2,3,4,5}
a.clear()
print(a)

set()


In [677]:
set1 = {1,2,3,4,5}
set2 = {4,5,6}
# set1.union(set2)

In [671]:
print(set1 | set2)

{1, 2, 3, 4, 5, 6}


In [672]:
set1 & set2

{4, 5}

In [673]:
set1.intersection(set2)

{4, 5}

In [674]:
set1,set2

({1, 2, 3, 4, 5}, {4, 5, 6})

In [675]:
set1.intersection_update(set2)

In [678]:
set1

{1, 2, 3, 4, 5}

In [679]:
set1.union_update(set2)

AttributeError: 'set' object has no attribute 'union_update'

In [681]:
set1,set2

({1, 2, 3, 4, 5}, {4, 5, 6})

In [682]:
set1-set2

{1, 2, 3}

In [683]:
set2-set1

{6}

In [684]:
set1.difference(set2)

{1, 2, 3}

In [685]:
set2.difference(set1)

{6}

In [686]:
set1 ^ set2

{1, 2, 3, 6}

In [690]:
(set1 | set2) - (set1 & set2)

{1, 2, 3, 6}

In [692]:
l = (1,2,3,4,5,6)
set(l)

{1, 2, 3, 4, 5, 6}

In [695]:
d = {"hello":45,"world":44}
set(d.keys()),set(d.values())

({'hello', 'world'}, {44, 45})

In [698]:
list(zip(d,d.values()))

[('hello', 45), ('world', 44)]

In [701]:
set2.issubset(set1)

False

In [704]:
{1,2,30}.issubset({1,2,3,4,5})

False

In [709]:
{1,2,30}.issubset({1,2,3,4,5})

False

In [711]:
{2,3,4,5,6}.issuperset({2,3})

True

In [713]:
1 in {2,3,1}

True

In [716]:
dict([[2,[5,6,7]],[5,6]])

{2: [5, 6, 7], 5: 6}

In [718]:
d = {2:2000,3:3000,4:4000}

In [723]:
d2 = {4:d,5:"hello",6:5.67}

In [724]:
d2

{4: {2: 2000, 3: 3000, 4: 4000}, 5: 'hello', 6: 5.67}

In [726]:
d2[4][3]

3000

In [727]:
type(d2[6])

float

In [729]:
d2.get(7,"Not found")

'Not found'

In [730]:
d2[7]

KeyError: 7

In [731]:
d2.get(7,"Not here")

'Not here'

In [734]:
d1 = {"name":"Devesh","Age":"?"}

In [735]:
d1

{'name': 'Devesh', 'Age': '?'}

In [736]:
d1['name'] = 'rohan'

In [742]:
d1["Age"] = 25

In [744]:
del d1["age"]

In [745]:
d1

{'name': 'rohan', 'Age': 25}

In [746]:
# taking inputs and saving them in a dictionary

variable_list = ['Name','Age','Gender','Mobile']

dict1 = {}
for i in variable_list:
    dict1[i]=input(f"Enter your {i}")
    
print(dict1)

Enter your Name devesh
Enter your Age 25
Enter your Gender male
Enter your Mobile 90099


{'Name': 'devesh', 'Age': '25', 'Gender': 'male', 'Mobile': '90099'}


In [747]:
dict1['Mobile'] = int(dict1['Mobile'])

In [752]:
temp = dict1.copy()

In [774]:
d = dict1.copy()

In [757]:
d.clear()
d

{}

In [762]:
d.pop('Name')

'devesh'

In [769]:
d.pop('Age',"Not fount")

'Not fount'

In [765]:
help(dict.pop)

Help on method_descriptor:

pop(...)
    D.pop(k[,d]) -> v, remove specified key and return the corresponding value.
    
    If the key is not found, return the default if given; otherwise,
    raise a KeyError.



In [777]:
d.popitem()

('Age', '25')

In [785]:
d.update({"Name":"Piyush",'year':2099})

In [786]:
d

{'Name': 'Piyush', 'year': 2099}

In [787]:
d2 = {}.fromkeys(list(range(10)),10)
d2

{0: 10, 1: 10, 2: 10, 3: 10, 4: 10, 5: 10, 6: 10, 7: 10, 8: 10, 9: 10}

In [792]:
l1 = [1,2,3,4,5]
l2 = ["one",'two','three','four','five']
d1 = {}

In [790]:
dict(zip(l1,l2))

{1: 'one', 2: 'two', 3: 'three', 4: 'four', 5: 'five'}

In [793]:
for i in range(len(l1)):
    d1[l1[i]] = l2[i]
print(d1)

{1: 'one', 2: 'two', 3: 'three', 4: 'four', 5: 'five'}


In [795]:
d1.items()

dict_items([(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five')])

In [796]:
d1.values()

dict_values(['one', 'two', 'three', 'four', 'five'])

In [797]:
d1.keys()

dict_keys([1, 2, 3, 4, 5])

In [799]:
# make a dict in which it hold a cube of 1 to 10 numbers
cube ={}
for i in range(1,11):
    cube[i] = i**3
print(cube)

{1: 1, 2: 8, 3: 27, 4: 64, 5: 125, 6: 216, 7: 343, 8: 512, 9: 729, 10: 1000}


In [800]:
only_even = { i:j for i,j in cube.items() if j%2==0}
only_even

{2: 8, 4: 64, 6: 216, 8: 512, 10: 1000}

In [802]:
t1 = (10, 20, 30, 40, 50)
t1[::-1]

(50, 40, 30, 20, 10)

In [804]:
t1 = ("Orange", [10, 20, 30], (5, 15, 25))


In [809]:
num = int(input())
for i in range(2,num):
    if num%i==0:
        print("its not a prime")
        break
    else:
        print("Its a prime")

 15


Its a prime
its not a prime


In [818]:
num = int(input())
factor = 0
l = []
for i in range(1,num):
    if num%i==0:
        factor+=1
        l.append(i)
if factor==1:
    print("its a Prime")
else:
    print('Its not a prime and can be divided by',l)

 53


its a Prime


In [819]:
t1 = ("Orange", [10, 20, 30], (5, 15, 25))

In [821]:
t1[1][1]

20

In [822]:
t1 = (50,)

In [823]:
t1

(50,)

In [824]:
tuple1 = (10, 20, 30, 40)
a,b,c,d = tuple1
print('a is ',a)
print('b is ',b)
print('c is ',c)
print('d is ',d)

a is  10
b is  20
c is  30
d is  40


In [825]:
tuple1 = (11, 22)
tuple2 = (99, 88)
tuple1,tuple2 = tuple2,tuple1
tuple1,tuple2

((99, 88), (11, 22))

In [826]:
t1 = (11, 22, 33, 44, 55, 66)
new_tuple = (t1[3],t1[4])
new_tuple

(44, 55)

In [827]:
t1 =  (11, [22, 33], 44, 55)
t1[1][0]=222
t1

(11, [222, 33], 44, 55)

In [828]:
t1 = (('a', 23),('b', 37),('c', 11), ('d',29))
for i in range(len(t1)):
    if t1[i][1]>t1[i+1][1]:
        

In [832]:
tuple1 = (('a', 23),('b', 37),('c', 11), ('d',29))
tuple2 = list(tuple1)
tuple2.sort()
print(tuple2)
list1 = list()
for i in tuple2:
 list1.append([i[1],i[0]])
list1.sort()
print(list1)
list3=[]
for j in list1:
 list3.append(tuple([j[1],j[0]]))
print(tuple(list3))


[('a', 23), ('b', 37), ('c', 11), ('d', 29)]
[[11, 'c'], [23, 'a'], [29, 'd'], [37, 'b']]
(('c', 11), ('a', 23), ('d', 29), ('b', 37))


In [833]:
t1 = (('a', 23),('b', 37),('c', 11), ('d',29))

In [841]:
t1
l1 = []
l2 = []
for i in t1:
    l1.append([i[1],i[0]])
l1.sort()
for i in l1:
    l2.append((i[1],i[0]))
l2 = tuple(l2)
l2

(('c', 11), ('a', 23), ('d', 29), ('b', 37))

In [843]:
t1 = (50, 10, 60, 70, 50)
t1.count(50)

2

In [844]:
count = 0
for i in t1:
    if i==50:
        count+=1
print(count)

2


In [849]:
t1 = (45, 45, 45, 45,45)
same = True
for i in t1:
    if t1[0]!=i:
        same = False
if same:
    print("All item are same")
else:
    print("No all item are not same")

All item are same


In [851]:
sample_set = {"Yellow", "Orange", "Black"}
sample_list = ["Blue", "Green", "Red"]
for i in sample_list:
    sample_set.add(i)
sample_set

{'Black', 'Blue', 'Green', 'Orange', 'Red', 'Yellow'}

In [860]:
set1 = {10, 20, 30, 40, 50}
set2 = {30, 40, 50, 60, 70}
set3 = set1 | set2
set3

{10, 20, 30, 40, 50, 60, 70}

In [853]:
set3

{30, 40, 50}

In [855]:
print(dir(set))

['__and__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__iand__', '__init__', '__init_subclass__', '__ior__', '__isub__', '__iter__', '__ixor__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__or__', '__rand__', '__reduce__', '__reduce_ex__', '__repr__', '__ror__', '__rsub__', '__rxor__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__xor__', 'add', 'clear', 'copy', 'difference', 'difference_update', 'discard', 'intersection', 'intersection_update', 'isdisjoint', 'issubset', 'issuperset', 'pop', 'remove', 'symmetric_difference', 'symmetric_difference_update', 'union', 'update']


In [856]:
set1.intersection(set2)

{30, 40, 50}

In [876]:
meth = input()
for i in dir(meth):
    if i[0]!= "_":
        print(i)

 set


capitalize
casefold
center
count
encode
endswith
expandtabs
find
format
format_map
index
isalnum
isalpha
isascii
isdecimal
isdigit
isidentifier
islower
isnumeric
isprintable
isspace
istitle
isupper
join
ljust
lower
lstrip
maketrans
partition
removeprefix
removesuffix
replace
rfind
rindex
rjust
rpartition
rsplit
rstrip
split
splitlines
startswith
strip
swapcase
title
translate
upper
zfill


In [870]:
set1 = {10, 20, 30, 40, 50}
set2 = {30, 40, 50, 60, 70}
print(set1|set2)
print(set1.union(set2))

{70, 40, 10, 50, 20, 60, 30}
{70, 40, 10, 50, 20, 60, 30}


In [871]:
set1 = {10, 20, 30}
set2 = {20, 40, 50}
set1 = set1-set2
print("set1: ",set1)

set1:  {10, 30}


In [873]:
set1 = {10, 20, 30, 40, 50}
set1 = set1 - {10,20,30}
print(set1)

{40, 50}


In [875]:
set1 = {10, 20, 30, 40, 50}
set2 = {30, 40, 50, 60, 70}
set1.difference(set2)
print(set1 ^ set2)

{20, 70, 10, 60}


In [879]:
set1 = {10, 20, 30, 40, 50}
set2 = {60, 70, 80, 90, 10}

if set1&set2 != {}:
    print(f"It has {set1&set2} element common")
else:
    print("No item is common")

It has {10} element common


In [885]:
set1 = {10, 20, 30, 40, 50}
set2 = {30, 40, 50, 60, 70}
set1 =  set1 ^ set2
set1

{10, 20, 60, 70}

In [888]:
set1 = {10, 20, 30, 40, 50}
set2 = {30, 40, 50, 60, 70}
set1 = set1 & set2
set1

{30, 40, 50}

In [889]:
keys = ['Ten', 'Twenty', 'Thirty']
values = [10, 20, 30]

d = {}
for i in range(len(keys)):
    d[keys[i]] = values[i]
d

{'Ten': 10, 'Twenty': 20, 'Thirty': 30}

In [894]:
dict1 = {'Ten': 10, 'Twenty': 20, 'Thirty': 30}
dict2 = {'Thirty': 30, 'Forty': 40, 'Fifty': 50}
dict1.update(dict2)
dict1

{'Ten': 10, 'Twenty': 20, 'Thirty': 30, 'Forty': 40, 'Fifty': 50}

In [892]:
print(dir(dict))

['__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__ior__', '__iter__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__or__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__ror__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'clear', 'copy', 'fromkeys', 'get', 'items', 'keys', 'pop', 'popitem', 'setdefault', 'update', 'values']


In [895]:
sampleDict = {
"class": {
"student": {
"name": "Anjali",
"marks": {
"physics": 70,
"history": 80
}
}
}
}

In [896]:
sampleDict

{'class': {'student': {'name': 'Anjali',
   'marks': {'physics': 70, 'history': 80}}}}

In [901]:
sampleDict['class']['student']['marks']['history']

80

In [905]:
employees = ['Shyam', 'Radha']
defaults = {'designation': 'Developer', 'salary': 8000}
d1 = {}
for i in employees:
    d1[i] = defaults
d1

{'Shyam': {'designation': 'Developer', 'salary': 8000},
 'Radha': {'designation': 'Developer', 'salary': 8000}}

In [902]:
dir(dict)

['__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__ior__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__or__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__ror__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'clear',
 'copy',
 'fromkeys',
 'get',
 'items',
 'keys',
 'pop',
 'popitem',
 'setdefault',
 'update',
 'values']

In [906]:
sample_dict = {
"name": "Anjali",
"subject": "Python",
"salary": 80000,
"city": "Ratlam"}
keys = ["name", "salary"]
d = {}
for i in keys:
    d[i] = sample_dict[i]
d

{'name': 'Anjali', 'salary': 80000}

In [908]:
sample_dict = {
"name": "Anjali",
"subject": "Python",
"salary": 80000,
"city": "Ratlam"}
keys = ["name", "salary"]
d = {}
for i in sample_dict.keys():
    if i not in keys:
        d[i] = sample_dict[i]
d

{'subject': 'Python', 'city': 'Ratlam'}

In [909]:
sample_dict = {'a': 100, 'b': 200, 'c': 300}
if 200 in sample_dict.values():
    print(" 200 is present in dict ")
else:
    print("its not present")

 200 is present in dict 


In [910]:
sample_dict = {
"name": "Radha",
"age":25,
"salary": 8000,
"city": "Indore"
}
sample_dict['location'] = sample_dict['city']
sample_dict.pop("city")
sample_dict

{'name': 'Radha', 'age': 25, 'salary': 8000, 'location': 'Indore'}

In [918]:
d = {
'Physics': 82,
'Math': 65,
'History': 75,
    "Hello":2
    
}
sub = list(d.keys())
marks = list(d.values())
min_marks = min(marks)
sub[marks.index(min_marks)]

'Hello'

In [919]:
sample_dict = {
'emp1': {'name': 'Shubham', 'salary': 7500},
'emp2': {'name': 'Lalit', 'salary': 8000},
'emp3': {'name': 'Bablu', 'salary': 500}
}
sample_dict['emp3']['salary'] = 85000
sample_dict

{'emp1': {'name': 'Shubham', 'salary': 7500},
 'emp2': {'name': 'Lalit', 'salary': 8000},
 'emp3': {'name': 'Bablu', 'salary': 85000}}

In [926]:
str1 = "iotaa"
print(str1[0],str1[len(str1)//2],str1[-1],sep="")

ita


In [934]:
str1 = "helloIOTAcademy"
mid = len(str1)//2
str1[mid-1:mid+2]

'OTA'

In [942]:
s1 = "IOTA"
s2 = "Academy"
mid = len(s1)//2
print(s1[:mid],s2,s1[mid:],sep="")

IOAcademyTA


In [945]:
str1 = "IoTaAcaDemy"
lower = 'abcdefghijklmnopqrstuvwxyz'
start = ""
end = ""
for i in str1:
    if i in lower:
        start+=i
    else:
        end+=i
print(start,end,sep="")

oacaemyITAD


In [950]:
str1 = "I@#OT26Aa^&c5ademy"
char = 0
num = 0
spec = 0
for i in str1:
    if i.isalpha():
        char+=1
    elif i.isdigit():
        num+=1
    else:
        spec+=1
print("total char",char)
print("total numbers ", num)
print('total special char ',spec)
        

total char 11
total numbers  3
total special char  4


In [948]:
dir(str)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'removeprefix',
 'removesuffix',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'stri